name: mutation testing

on:
  push:
    branches:
      - main
      - stryker

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:mutation
        env:
          CI: true
