name: Snyk vulnerability test
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ 7ecdd6c7-af2d-4163-814d-a536786dade6 }}